In [2]:
import numpy as np

data_ndarray = np.array([10,20,30])
data_ndarray

array([10, 20, 30])

In [3]:
import csv

file = open('nyc_taxis.csv','r')
taxi_list = list(csv.reader(file))

In [4]:
taxi_list = taxi_list[1:] #remove header

In [5]:
#convert values to float
converted_taxi_list = []
for row in taxi_list:
    converted_row = []
    for item in row:
        converted_row.append(float(item))
    converted_taxi_list.append(converted_row)

In [6]:
taxi = np.array(converted_taxi_list)
taxi

array([[2.016e+03, 1.000e+00, 1.000e+00, ..., 1.165e+01, 6.999e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 8.000e+00, 5.430e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 0.000e+00, 3.780e+01,
        2.000e+00],
       ...,
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 5.000e+00, 6.334e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 8.950e+00, 4.475e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 0.000e+00, 5.484e+01,
        2.000e+00]])

In [7]:
taxi_shape = np.shape(taxi)
taxi_shape

(2013, 15)

In [8]:
taxi.shape

(2013, 15)

In [9]:
row_0 = taxi[0]
row_0

array([2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
       4.000e+00, 2.100e+01, 2.037e+03, 5.200e+01, 8.000e-01, 5.540e+00,
       1.165e+01, 6.999e+01, 1.000e+00])

In [10]:
rows_391_to_500 = taxi[391:501] #rows indexes
rows_391_to_500

array([[2.016e+03, 1.000e+00, 2.000e+00, ..., 0.000e+00, 2.630e+01,
        2.000e+00],
       [2.016e+03, 1.000e+00, 2.000e+00, ..., 3.000e+00, 3.030e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 2.000e+00, ..., 6.670e+00, 4.001e+01,
        1.000e+00],
       ...,
       [2.016e+03, 1.000e+00, 4.000e+00, ..., 0.000e+00, 5.534e+01,
        2.000e+00],
       [2.016e+03, 1.000e+00, 4.000e+00, ..., 3.090e+00, 1.339e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 4.000e+00, ..., 4.000e+00, 2.680e+01,
        1.000e+00]])

In [11]:
row_21_column_5 = taxi[21,5] #select specific row, column
row_21_column_5

4.0

In [14]:
columns_1_4_7 = taxi[:,[1,4,7]]
row_99_columns_5_to_8 = taxi[99,5:9]
rows_100_to_200_column_14 = taxi[100:201,14]

In [17]:
fare_amount = taxi[:,9]
fee_amount = taxi[:,10]
fare_and_fees = fare_amount + fee_amount
fare_and_fees

array([52.8, 46.3, 37.8, ..., 52.8, 35.8, 49.3])

In [19]:
trip_distance_miles = taxi[:,7]
trip_length_seconds = taxi[:,8]

trip_length_hours = trip_length_seconds / 3600 # 3600 seconds is one hour

trip_mph = trip_distance_miles/trip_length_hours
trip_mph

array([37.11340206, 38.58157895, 31.27222982, ..., 22.29907867,
       42.41551247, 36.90473407])

In [20]:
mph_min = trip_mph.min()
mph_min

0.0

In [21]:
trip_mph.max()

82800.0

In [22]:
trip_mph.mean()

169.98315083655157

In this mission we learned:

How vectorization makes our code faster.  
About n-dimensional arrays, and NumPy's ndarrays.  
How to select specific items, rows, columns, 1D slices, and 2D slices from ndarrays.  
How to apply simple calculations to entire ndarrays.  
How to use vectorized methods to perform calculations across either axis of ndarrays.  
In the next mission, we'll continue to work with the NYC taxi data as we learn about boolean indexing, one of the most powerful tools when working with data in NumPy and pandas.