In [2]:
import numpy as np
taxi = np.genfromtxt('nyc_taxis.csv',delimiter=',') #to read files into NumPy ndarrays.
taxi

array([[      nan,       nan,       nan, ...,       nan,       nan,
              nan],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 1.165e+01, 6.999e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 8.000e+00, 5.430e+01,
        1.000e+00],
       ...,
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 5.000e+00, 6.334e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 8.950e+00, 4.475e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 0.000e+00, 5.484e+01,
        2.000e+00]])

In [3]:
taxi.shape

(2014, 15)

In [5]:
import csv
# import nyc_taxi.csv as a list of lists
f = open("nyc_taxis.csv", "r")
taxi_list = list(csv.reader(f))

# remove the header row
taxi_list = taxi_list[1:]

# convert all values to floats
converted_taxi_list = []
for row in taxi_list:
    converted_row = []
    for item in row:
        converted_row.append(float(item))
    converted_taxi_list.append(converted_row)

# start writing your code below this comment
taxi = np.array(converted_taxi_list)
taxi

array([[2.016e+03, 1.000e+00, 1.000e+00, ..., 1.165e+01, 6.999e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 8.000e+00, 5.430e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 0.000e+00, 3.780e+01,
        2.000e+00],
       ...,
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 5.000e+00, 6.334e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 8.950e+00, 4.475e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 0.000e+00, 5.484e+01,
        2.000e+00]])

In [10]:
taxi = np.genfromtxt('nyc_taxis.csv',delimiter=',',skip_header=1) #skip_header is number of rows to skip not index
taxi.shape

(2013, 15)

In [13]:
a = np.array([1,2,3,4,5])
b = np.array(['blue','blue','red','blue'])
c = np.array([80,103.4,96.9,200.3])
a_bool = a<3
print('a_bool:',a_bool)
b_bool = b == 'blue'
print('b_bool:',b_bool)
c_bool = c>100
print('c_bool:',c_bool)

a_bool: [ True  True False False False]
b_bool: [ True  True False  True]
c_bool: [False  True False  True]


In [18]:
#select using boolean
pickup_month = taxi[:,1] #month in 2nd column
february_bool = pickup_month == 2
february = pickup_month[february_bool]
february_rides = february.shape[0]
february_rides

176

In [19]:
tip_amount = taxi[:,12]
tip_bool = tip_amount>50
top_tips = taxi[tip_bool,5:14]
top_tips

array([[4.000e+00, 2.000e+00, 2.145e+01, 2.004e+03, 5.200e+01, 8.000e-01,
        0.000e+00, 5.280e+01, 1.056e+02]])

In [20]:
taxi_modified = taxi.copy()
taxi_modified[1066,5]=1
taxi_modified[:,0]=16
taxi_modified[550:552,7] = taxi_modified[:,7].mean()
taxi_modified

array([[16.  ,  1.  ,  1.  , ..., 11.65, 69.99,  1.  ],
       [16.  ,  1.  ,  1.  , ...,  8.  , 54.3 ,  1.  ],
       [16.  ,  1.  ,  1.  , ...,  0.  , 37.8 ,  2.  ],
       ...,
       [16.  ,  6.  , 30.  , ...,  5.  , 63.34,  1.  ],
       [16.  ,  6.  , 30.  , ...,  8.95, 44.75,  1.  ],
       [16.  ,  6.  , 30.  , ...,  0.  , 54.84,  2.  ]])

In [22]:
taxi_copy = taxi.copy()
total_amount = taxi_copy[:,13]
total_amount[total_amount<0]=0
total_amount

array([69.99, 54.3 , 37.8 , ..., 63.34, 44.75, 54.84])

In [24]:
zeros = np.zeros([taxi.shape[0],1]) #create a new column filled with zeros
zeros

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [26]:
taxi_modified = np.concatenate([taxi,zeros],axis=1)
taxi_modified

array([[2.016e+03, 1.000e+00, 1.000e+00, ..., 6.999e+01, 1.000e+00,
        0.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 5.430e+01, 1.000e+00,
        0.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 3.780e+01, 2.000e+00,
        0.000e+00],
       ...,
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 6.334e+01, 1.000e+00,
        0.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 4.475e+01, 1.000e+00,
        0.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 5.484e+01, 2.000e+00,
        0.000e+00]])

In [27]:
taxi_modified[taxi_modified[:,5]==2,15]=1
taxi_modified[taxi_modified[:,5]==3,15]=1
taxi_modified[taxi_modified[:,5]==5,15]=1
taxi_modified

array([[2.016e+03, 1.000e+00, 1.000e+00, ..., 6.999e+01, 1.000e+00,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 5.430e+01, 1.000e+00,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 3.780e+01, 2.000e+00,
        1.000e+00],
       ...,
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 6.334e+01, 1.000e+00,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 4.475e+01, 1.000e+00,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 5.484e+01, 2.000e+00,
        1.000e+00]])

In [31]:
jfk = taxi[taxi[:,6]==2]
print(jfk)
jfk_count = jfk.shape[0]
jfk_count

[[2.016e+03 1.000e+00 1.000e+00 ... 5.280e+01 1.056e+02 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 0.000e+00 3.730e+01 2.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 0.000e+00 5.834e+01 2.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 0.000e+00 3.800e+00 2.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 0.000e+00 5.834e+01 2.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 5.660e+00 6.400e+01 1.000e+00]]


285

In [32]:
languardia = taxi[taxi[:,6]==3]
languardia_count = languardia.shape[0]
languardia_count

308

In [33]:
newark = taxi[taxi[:,6] == 5]
newark_count = newark.shape[0]
newark_count

2

In [34]:
#calculate the mean value
trip_mph = taxi[:,7]/(taxi[:,8]/3600)
cleaned_taxi = taxi[trip_mph<100]
mean_distance = cleaned_taxi[:,7].mean()
mean_length = cleaned_taxi[:,8].mean()
mean_total_amount = cleaned_taxi[:,13].mean()